- name: Add orchestrator key
  apt_key:
    url: "https://packagecloud.io/github/orchestrator/gpgkey"
    state: present

- name: Add orchestrator repo
  apt_repository:
    repo: deb https://packagecloud.io/github/orchestrator/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main
    state: present

- name: Install orchestrator necessary packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - orchestrator-cli
    - orchestrator
    - curl
    - jq
