---
- import_tasks: install_with_apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: install_with_yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create my.cnf because root user require password on this setup
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Configure orchestrator
  template:
    src: orchestrator.conf.j2
    dest: /etc/orchestrator.conf.json
    owner: root
    group: root
    mode: 0600
  notify: restart orchestrator

- meta: flush_handlers

- name: Install orchestrator-client
  copy:
    src: orchestrator-client
    dest: /usr/bin/orchestrator-client
    mode: 0755

- name: Add first mysql server into orchestrator
  shell: orchestrator-client -c discover -i {{ groups['mysql'][0] }}:{{ mysql_port }}
