---
- name: Install haproxy with apt
  apt: pkg=haproxy state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install haproxy with yum
  yum: pkg=haproxy state=present update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Init haproxy env
  file: path=/run/haproxy state=directory
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Change the haproxy_connect_any to permissive
  command: setsebool -P haproxy_connect_any=1
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Set mysqlchk socket
  template:
    src: mysqlchk.socket.j2
    dest: /etc/systemd/system/mysqlchk.socket
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"

- name: Set mysqlchk service
  template:
    src: mysqlchk@.service.j2
    dest: /etc/systemd/system/mysqlchk@.service
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"

- name: Set mysqlchk script
  template:
    src: mysqlchk.j2
    dest: "{{ mysqlchk_path }}"
    mode: 0755
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"
