---
- name: Install haproxy with apt
  apt: pkg=haproxy state=present update_cache=yes
  environment: '{{ proxy_env | default({}) }}'
  when: ansible_os_family == "Debian"
  tags: install_haproxy

- block:
    - name: Install haproxy with yum
      yum: pkg=haproxy state=present update_cache=yes

    - name: Fix haproxy.service to mkdir /run/haproxy
      lineinfile:
        path: /usr/lib/systemd/system/haproxy.service
        regexp: '^ExecStartPre'
        line: ExecStartPre=/bin/mkdir -p /run/haproxy

    - name: Change the haproxy_connect_any to permissive
      command: setsebool -P haproxy_connect_any=1
  environment: '{{ proxy_env | default({}) }}'
  when: ansible_os_family == "RedHat"
  tags: install_haproxy

- name: Set haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Set mysqlchk socket
  template:
    src: mysqlchk.socket.j2
    dest: /etc/systemd/system/mysqlchk.socket
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"

- name: Set mysqlchk service
  template:
    src: mysqlchk@.service.j2
    dest: /etc/systemd/system/mysqlchk@.service
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"

- name: Set mysqlchk script
  template:
    src: mysqlchk.j2
    dest: "{{ mysqlchk_path }}"
    mode: 0755
  notify: restart mysqlchk
  delegate_to: "{{ item }}"
  with_items: "{{ groups['mysql'] }}"
