---
- name: Prepare Ubuntu for work with Ansible
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Ensure python2.x is available
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Global Setup
  hosts: all
  become: true

  tasks:
    - name: Ensure hostname valid on all hosts
      command: hostnamectl set-hostname {{ inventory_hostname }}
      when: inventory_hostname != ansible_facts['nodename']

    - name: Install first necessary packages (apt)
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - htop
        - atop
        - mc
        - nano
        - curl
      environment: '{{ proxy_env | default({}) }}'
      when: ansible_os_family == "Debian"
    
    - name: Install first necessary packages (yum)
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - htop
        - atop
        - mc
        - nano
        - curl
      environment: '{{ proxy_env | default({}) }}'
      when: ansible_os_family == "RedHat"

    - name: Add hosts
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
      when: hostvars[item].ansible_host is defined
      with_inventory_hostnames:
        - all

  roles:
    - ufw
    - haproxy

- name: Mysql Setup
  hosts: mysql
  become: true

  roles:
    - mysql

- name: Orchestrator Setup
  hosts: orchestrator
  become: true

  roles:
    - orchestrator
