---
- hosts: localhost
  connection: local
  tasks:
    - add_host:
        name: "{{ slave }}"
        groups: slaves
      changed_when: false

- name: Manually make slave replicate master
  hosts: slaves
  
  tasks:
    - name: Set replication master
      mysql_replication:
        mode: changemaster
        master_host: "{{ master }}"
        master_port: "{{ mysql_port }}"
        master_user: "{{ mysql_replication_user.name }}"
        master_password: "{{ mysql_replication_user.password }}"
        master_auto_position: 1
        login_user: "{{ mysql_root_user.name }}"
        login_password: "{{ mysql_root_user.password }}"
        login_port: "{{ mysql_port }}"

    - name: Start replication
      mysql_replication:
        mode: startslave
        login_user: "{{ mysql_root_user.name }}"
        login_password: "{{ mysql_root_user.password }}"
        login_port: "{{ mysql_port }}"

    - name: Check replication status
      mysql_replication:
        mode: getslave
        login_user: "{{ mysql_root_user.name }}"
        login_password: "{{ mysql_root_user.password }}"
        login_port: "{{ mysql_port }}"
