---
- block:
    - name: Add Oracle key (apt)
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 5072E1F5

    - name: Add Oracle repo (apt)
      apt_repository:
        repo: deb http://repo.mysql.com/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} mysql-5.7
        state: present

    - name: Install mysql necessary packages (apt)
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - mysql-client
        - mysql-utilities
        - python-mysqldb
  environment: '{{ proxy_env | default({}) }}'
  when: ansible_os_family == "Debian"
  tags: install_mysql_necessary_packages
  
- block:
    - name: Add Oracle repo (yum)
      yum:
        name: "http://repo.mysql.com/mysql57-community-release-el7-11.noarch.rpm"
        state: present

    - name: Install mysql necessary packages (yum)
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - mysql-community-client
        - mysql-utilities
        - MySQL-python
  environment: '{{ proxy_env | default({}) }}'
  when: ansible_os_family == "RedHat"
  tags: install_mysql_necessary_packages

- name: Create my.cnf because root user require password on this setup
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- import_tasks: master.yml
  when: mysql_role is defined and mysql_role == 'master'

- import_tasks: slave.yml
  when: mysql_role is defined and mysql_role == 'slave'
