- name: Disable read_only on master
  mysql_variables: variable=read_only value=OFF

- name: Ensure replication user exists on master
  mysql_user:
    name: "{{ mysql_replication_user.name }}"
    host: "{{ mysql_replication_user.host | default('%') }}"
    password: "{{ mysql_replication_user.password }}"
    priv: "{{ mysql_replication_user.priv | default('*.*:REPLICATION SLAVE,REPLICATION CLIENT') }}"
    state: present
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
  when: mysql_replication_user

- name: Ensure root user exists on master
  mysql_user:
    name: "{{ mysql_root_user.name }}"
    host: "{{ mysql_root_user.host | default('%') }}"
    password: "{{ mysql_root_user.password }}"
    priv: "{{ mysql_root_user.priv | default('*.*:ALL,GRANT') }}"
    state: present
    login_port: "{{ mysql_port }}"
  ignore_errors: yes
