- import_tasks: server.yml

- name: Check replication on slave
  mysql_replication:
    mode: getslave
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
  register: replica_status
  ignore_errors: yes

- stat:
    path: "{{ backup_src }}"
  register: dump

# https://github.com/ansible/ansible-modules-core/issues/932
- name: Unpack sql dump
  shell: gunzip < "{{ backup_src }}" > /tmp/dump.sql
  when: 
    - replica_status.Is_Slave|bool != true   # TODO: error when replica is configured
    - dump.stat.exists is defined and dump.stat.exists

- name: Seed database with dump
  mysql_db:
    name: all
    state: import
    target: /tmp/dump.sql
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.Is_Slave|bool != true
    - dump.stat.exists is defined and dump.stat.exists

- name: Removing temporary dump
  file:
    path: /tmp/dump.sql
    state: absent

- name: Set replication master
  mysql_replication:
    mode: changemaster
    master_host: "{{ hostvars[item].ansible_host }}"
    master_port: "{{ mysql_port }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.password }}"
    master_auto_position: 1
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.Is_Slave|bool != true
    - hostvars[item].mysql_role == 'master'
  with_items:
    - "{{ groups['mysql'] }}"

- name: Start replication
  mysql_replication:
    mode: startslave
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
  when:
    - replica_status.Is_Slave|bool != true

- name: Check replication status
  mysql_replication:
    mode: getslave
    login_user: "{{ mysql_root_user.name }}"
    login_password: "{{ mysql_root_user.password }}"
    login_port: "{{ mysql_port }}"
