---
# Based on https://github.com/cturner80/digital-ocean-ansible/blob/master/handlers.yml
# The MIT License (MIT)
# Copyright (c) 2014 Chris Turner
# Modify by Filipp Kucheryavy <filipp.s.frizzy@gmail.com>


# to verify ufw configuration run:
# sudo ufw status verbose

- block:
    - name: Install ufw with apt
      apt: pkg=ufw state=present
      when: ansible_os_family == 'Debian'

    - name: Install epel-release with yum
      yum: pkg=epel-release state=present
      when: ansible_os_family == 'RedHat'

    - name: Install ufw with yum
      yum: pkg=ufw state=present
      when: ansible_os_family == 'RedHat'
  environment: '{{ proxy_env | default({}) }}'
  tags: install_ufw

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
  notify:
    - restart ufw

- name: Allow Hosts
  ufw:
    rule: allow
    src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups['all'] }}"
  notify:
    - restart ufw

- name: Allow local networks
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  notify:
    - restart ufw

- name: Enable ufw logging
  ufw: logging=on
  notify:
    - restart ufw

- name: Enable ufw
  ufw: state=enabled

- name: Disable firewalld in CentOS or Red Hat Enterprise Linux
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
